# This is a basic workflow to help you get started with Actions

name: Scrap GITHUB Data From Data Repo

# Controls when the workflow will run
on:
  workflow_call:
    secrets:
      GIT_ACCESS_TOKEN:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-data:
    name: Scrape data from GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout leaderboad-data Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          ref: develop  # Replace with the branch you want to checkout
          
      - name: Checkout leaderboard Repository   
        uses: actions/checkout@v4
        with:
          repository: beckn/leaderboard
          path: ./leaderboard
          sparse-checkout: |
            scripts

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm i octokit
        
      - name: Scrape GitHub data
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 1
          command: node scripts/pullHistoricalGitHubActivitiesForDataRepo.js
          on_retry_command: git checkout .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: "beckn"

      - name: Generate markdown files for new contributors
        run: node scripts/generateNewContributorsForDataRepo.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: "beckn"
      
      - name: Check for folder creation
        run: ls -al

      - name: Check for folder creation echo
        run: |
          echo "Listing files in data-repo directory:"
          ls -la data-repo
          echo "Git status before adding files:"
          git status

      - name: Git Status
        run: git status

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
  
          if [ -n "$(git status --porcelain)" ]; then
            git add data contributors
            git commit -m "🌍 Update JSON - $(date -d '+5 hours +30 minutes' +'%d %b %Y | %I:%M %p')"
            git push
          else
            echo "Nothing to commit"
          fi
